### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by chandrasekhar4u** [praducg/NodeWitClient#1]
getting below error when we run node index.js

```
C:\Users\user\pradeep_src\NodeWitClient\lib\wit.js:18
  const {
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (C:\Users\Chandra\pradeep_src\NodeWitClient\index.js:4:8)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by praducg** [comment]
Update node.js that's what I told Yesterday.Check stackworkflow

**Comment by chandrasekhar4u** [comment]
yep it's working with node --harmony_destructuring index.js
